name: linkfive_purchases_example
description: Demonstrates how to use the linkfive_purchases plugin.
version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  linkfive_purchases: ^1.5.0
    #path: ../packages/linkfive_purchases
  linkfive_purchases_provider: ^1.5.0
    #path: ../packages/linkfive_purchases_provider
  in_app_purchases_paywall_ui: ^0.5.0
    #path: ../../in_app_purchases_paywall/packages/in_app_purchases_paywall_ui
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_bloc: ^7.3.3
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/apikey.json
