name: linkfive_purchases
description: LinkFive Purchases flutter sdk. This will allow your app to use the LinkFive subscription service.
version: 1.1.0
homepage: https://www.linkfive.io
repository: https://github.com/LinkFive/flutter-purchases-sdk
issue_tracker: https://github.com/LinkFive/flutter-purchases-sdk/issues
documentation: https://github.com/LinkFive/flutter-purchases-sdk

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^1.0.6
  http: ^0.13.3
  package_info_plus: ^1.0.3
  device_info_plus: ^2.0.1
  in_app_purchase_ios: ^0.1.3
  in_app_purchase_platform_interface: ^1.1.0
  in_app_purchase_android: ^0.1.4+1
  in_app_purchases_interface: ^0.0.5
    #path: ../in_app_purchases_paywall/packages/in_app_purchases_interface
  in_app_purchases_intl: ^0.0.2
    #path: ../in_app_purchases_paywall/packages/in_app_purchases_intl

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.linkfive.linkfive_purchases
        pluginClass: LinkFivePurchasesPlugin
      ios:
        pluginClass: LinkfivePurchasesPlugin
