name: linkfive_purchases_provider
description: linkfive_purchases wrapped in an easy to use Provider
version: 1.2.0
homepage: https://www.linkfive.io
repository: https://github.com/LinkFive/flutter-purchases-sdk
issue_tracker: https://github.com/LinkFive/flutter-purchases-sdk/issues
documentation: https://github.com/LinkFive/flutter-purchases-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  provider: ^6.0.1
  linkfive_purchases: ^1.2.0
    #path: ../linkfive_purchases

flutter: